In [14]:
# cloning GitHub Repo
!git clone https://github.com/chase-kusterer/BASD.git

# changing directory
import os
repo_name = '/content/BASD/'
os.chdir(repo_name)

# checking results
print(f"Current working directory changed to: {os.getcwd()}")

Cloning into 'BASD'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 53 (delta 15), reused 38 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (53/53), 5.20 MiB | 26.10 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Current working directory changed to: /content/BASD

<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />

<br><h1>Essential DataFrame Methods</h1>
DAT-7470 - Business Analysis with Structured Data<br>
Guided Analysis Notebook<br><br>

Written by Chase Kusterer - Faculty of Analytics <br>
Hult International Business School <br>
<a href="https://chase-kusterer.github.io/">https://chase-kusterer.github.io/</a><br><br><br><br><br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<br>
<h2>Part I: Practice - Importing Excel Data into Python</h2>
In the previous script, we learned how to import data into Python using the <strong>read_excel(&nbsp;)</strong> method from <em>pandas</em>. Every time we launch a Python script or a Jupyter Notebook, our working environment gets reset and we need to perform these steps one more time. To start off this script, you are tasked with importing the data.
<br><br>
<h4>a) Import pandas and the diamonds dataset.</h4>

In [18]:
# importing packages as pd
import pandas as pd


# storing the path to the dataset
file = "/content/BASD/datasets/diamonds.xlsx"


# reading the file into Python through pandas
diamonds = pd.read_excel('/content/BASD/datasets/diamonds.xlsx')


# checking results (first TEN rows of the dataset)
diamonds.head(n = 10)

   Obs  carat  color  clarity  cut  channel  store  price
0    1   0.32      3        7    0        0      7   1375
1    2   0.35      5        7    1        0      7   1680
2    3   0.40      4        7    1        0      7   2245
3    4   0.59      5        7    0        0      3   2495
4    5   0.72      7        8    0        0      8   2699
5    6   0.72      6        8    0        0      8   2699
6    7   0.51      2        8    0        0      3   2895
7    8   1.00      8        9    0        0      7   2900
8    9   1.00      8        9    0        0      8   2999
9   10   0.47      2        7    0        0      7   3080

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h2>Part II: Auditing Data Quality - Fixing Feature Types</h2>

Now that the diamonds dataset has been instantiated, its methods can be accessed using method chaining. All DataFrame methods can be accessed using <strong>help(pd.DataFrame)</strong>. After import, a common step in the analytical process is to audit data quality. The following DataFrame methods are critical for this task, and they will also help to validate many of the assumptions from the <em>Finding the "Best" Diamond on a Budget</em> case study.

* <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html">.info(&nbsp;)</a>
* <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html">.describe(&nbsp;)</a>
* <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html">.value_counts(&nbsp;)</a>

<br>
Each method will be explored throughout this script, starting with <strong>.info(&nbsp;)</strong>. This method gives us key information related to the label, count, and data type of each column, as well as the size of the DataFrame in terms of memory usage (beyond the scope of this course).

In [19]:
# analyzing info related to each feature
diamonds.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Obs      409 non-null    int64
 1   carat    409 non-null    float64
 2   color    409 non-null    int64
 3   clarity  409 non-null    int64
 4   cut      409 non-null    int64
 5   channel  409 non-null    int64
 6   store    409 non-null    int64
 7   price    409 non-null    int64
dtypes: float64(1), int64(7)
memory usage: 25.7 KB

In [20]:
diamonds.describe()

,Obs,carat,color,clarity,cut,channel,store,price
count,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000
mean,219.317848,1.055968,4.227384,5.056235,0.376528,1.672372,9.132029,6488.229829
std,120.894528,0.418013,1.810815,1.573141,0.485108,0.656972,2.589037,4414.425161
min,1.000000,0.320000,1.000000,1.000000,0.000000,0.000000,1.000000,878.000000
25%,119.000000,0.720000,3.000000,4.000000,0.000000,2.000000,10.000000,3490.000000
50%,221.000000,1.020000,4.000000,5.000000,0.000000,2.000000,10.000000,5550.000000
75%,323.000000,1.210000,6.000000,6.000000,1.000000,2.000000,11.000000,8089.000000
max,425.000000,2.480000,9.000000,9.000000,1.000000,2.000000,11.000000,27575.000000

<br>

<div style = "width:image width px; font-size:80%; text-align:center;"><img src="https://github.com/chase-kusterer/BASD/blob/main/script_images/chapter-X3-breakdown-of-info().png?raw=1" width="500" height="500" style="padding-bottom:0.5em;"> <em>Figure 12.1: Breaking down .info(&nbsp;).</em></div>

<br>
<h4>a) From the output above, which features seem to have improper data types?</h4>
Remember to check the <a href="miller_mds_two_months_salary_case.pdf">documentation on the diamonds dataset</a> as needed.

In [21]:
# features with improper data types
diamonds.describe()


# Rationale for above
"""
obs
store
remove cut & channel has no numerics
cut to boolean

"""

'\nobs\nstore\nremove cut & channel has no numerics\ncut to boolean\n\n'

<br>

~~~

  ..---..       ..---..       ..---..       ..---..       ..---..
 /       \     /       \     /       \     /       \     /       \
|         |   |         |   |         |   |         |   |         |
:         ;   :         ;   :         ;   :         ;   :         ;
 \  \~/  /     \  \~/  /     \  \~/  /     \  \~/  /     \  \~/  /
  `, Y ,'       `, Y ,'       `, Y ,'       `, Y ,'       `, Y ,'
   |_|_|         |_|_|         |_|_|         |_|_|         |_|_|
   |===|         |===|         |===|         |===|         |===|
   |===|         |===|         |===|         |===|         |===|
    \_/           \_/           \_/           \_/           \_/
~~~

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h3>Fixing Data Types</h3>
Making changes to data types in Python can be done with ease with the use of a <a href="https://docs.python.org/3/tutorial/datastructures.html#dictionaries">dictionary</a>. A guideline for developing such a tool can be found below. Note that we only need to specify the <em>{feature : data type}</em> of the features we would like to change. Also note that once we have analyzed the results of <strong>.info(&nbsp;)</strong> and understand which data types to convert, we generally apply this in the same step as when we import the data.<br><br>

~~~
{"feature" : data type,     # feature 1
 "feature" : data type,     # feature 2
 ...}                       # and so on
~~~

<br>

<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<h4>b) Convert data types as indicated by the table below.</h4>
Complete the code to create a data type dictionary. Then, import the diamonds dataset one more time, reading in the data types using the <em>dtypes</em> argument from <strong>pd.read_excel(&nbsp;)</strong>. Note that <em>Obs</em> is not listed as it is not going to be used going forward (its ordering is arbitrary and it should not be used in our analysis). Call help on <strong>pd.read_excel(&nbsp;)</strong> to discover which argument can be applied to avoid importing <em>Obs</em>.
<br><br>
<div style = "width:image width px; font-size:80%; text-align:center;">
<table align="center">
<col width="100">
<col width="10">   
<col width="100">
    <tr>
        <th>Feature</th>
        <th>    | </th>
        <th>Original Type</th>
        <th>    | </th>
        <th>New Type</th>
        <th>    | </th>
        <th>Rationale for Change</th>
    </tr>
    <tr>
        <td>channel</td>
        <td>    | </td>
        <td> int</td>
        <td>    | </td>
        <td> str</td>
        <td>    | </td>
        <td> feature is categorical (pre-processing step)</td>
    </tr>
    <tr>
        <td>store</td>
        <td>    | </td>
        <td> int</td>
        <td>    | </td>
        <td> str</td>
        <td>    | </td>
        <td> feature is categorical (pre-processing step)</td>
    </tr>   
    
          Table 14.1: Sample documentation for data type changes.
</table></div><br>

In [9]:
# help file for pd.read_excel
help(pd.read_excel)

Help on function read_excel in module pandas.io.excel._base:

read_excel(io, sheet_name: 'str | int | list[IntStrT] | None' = 0, *, header: 'int | Sequence[int] | None' = 0, names: 'SequenceNotStr[Hashable] | range | None' = None, index_col: 'int | str | Sequence[int] | None' = None, usecols: 'int | str | Sequence[int] | Sequence[str] | Callable[[str], bool] | None' = None, dtype: 'DtypeArg | None' = None, engine: "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb', 'calamine'] | None" = None, converters: 'dict[str, Callable] | dict[int, Callable] | None' = None, true_values: 'Iterable[Hashable] | None' = None, false_values: 'Iterable[Hashable] | None' = None, skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, parse_dates: 'list | dict | bool' = False, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'dict[Hashable, str] | str | None' = None, thousands: 'str | None' = None, decimal: 'str' = '.', comment: 'str | None' = None, skipfooter: 'int' = 0, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>, engine_kwargs: 'dict | None' = None) -> 'DataFrame | dict[IntStrT, DataFrame]'
    Read an Excel file into a ``pandas`` ``DataFrame``.

    Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
    read from a local filesystem or URL. Supports an option to read
    a single sheet or a list of sheets.

    Parameters
    ----------
    io : str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.

        .. deprecated:: 2.1.0
            Passing byte strings is deprecated. To read from a
            byte string, wrap it in a ``BytesIO`` object.
    sheet_name : str, int, list, or None, default 0
        Strings are used for sheet names. Integers are used in zero-indexed
        sheet positions (chart sheets do not count as a sheet position).
        Lists of strings/integers are used to request multiple sheets.
        Specify ``None`` to get all worksheets.

        Available cases:

        * Defaults to ``0``: 1st sheet as a `DataFrame`
        * ``1``: 2nd sheet as a `DataFrame`
        * ``"Sheet1"``: Load sheet with name "Sheet1"
        * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
          as a dict of `DataFrame`
        * ``None``: All worksheets.

    header : int, list of int, default 0
        Row (0-indexed) to use for the column labels of the parsed
        DataFrame. If a list of integers is passed those row positions will
        be combined into a ``MultiIndex``. Use None if there is no header.
    names : array-like, default None
        List of column names to use. If file contains no header row,
        then you should explicitly pass header=None.
    index_col : int, str, list of int, default None
        Column (0-indexed) to use as the row labels of the DataFrame.
        Pass None if there is no such column.  If a list is passed,
        those columns will be combined into a ``MultiIndex``.  If a
        subset of data is selected with ``usecols``, index_col
        is based on the subset.

        Missing values will be forward filled to allow roundtripping with
        ``to_excel`` for ``merged_cells=True``. To avoid forward filling the
        missing values use ``set_index`` after reading the data instead of
        ``index_col``.
    usecols : str, list-like, or callable, default None
        * If None, then parse all columns.
        * If str, then indicates comma separated list of Excel column letters
          and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
          both sides.
        * If list of int, then indicates list of column numbers to be parsed
          (0-indexed).
        * If list of string, then indicates list of column names to be parsed.
        * If callable, then evaluate each column name against it and parse the
          column if the callable returns ``True``.

        Returns a subset of the columns according to behavior above.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use ``object`` to preserve data as stored in Excel and not interpret dtype,
        which will necessarily result in ``object`` dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
        If you use ``None``, it will infer the dtype of each column based on the data.
    engine : {'openpyxl', 'calamine', 'odf', 'pyxlsb', 'xlrd'}, default None
        If io is not a buffer or path, this must be set to identify io.
        Engine compatibility :

        - ``openpyxl`` supports newer Excel file formats.
        - ``calamine`` supports Excel (.xls, .xlsx, .xlsm, .xlsb)
          and OpenDocument (.ods) file formats.
        - ``odf`` supports OpenDocument file formats (.odf, .ods, .odt).
        - ``pyxlsb`` supports Binary Excel files.
        - ``xlrd`` supports old-style Excel files (.xls).

        When ``engine=None``, the following logic will be used to determine the engine:

        - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
          then `odf <https://pypi.org/project/odfpy/>`_ will be used.
        - Otherwise if ``path_or_buffer`` is an xls format, ``xlrd`` will be used.
        - Otherwise if ``path_or_buffer`` is in xlsb format, ``pyxlsb`` will be used.
        - Otherwise ``openpyxl`` will be used.
    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can
        either be integers or column labels, values are functions that take one
        input argument, the Excel cell content, and return the transformed
        content.
    true_values : list, default None
        Values to consider as True.
    false_values : list, default None
        Values to consider as False.
    skiprows : list-like, int, or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int) at the
        start of the file. If callable, the callable function will be evaluated
        against the row indices, returning True if the row should be skipped and
        False otherwise. An example of a valid callable argument would be ``lambda
        x: x in [0, 2]``.
    nrows : int, default None
        Number of rows to parse.
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values. By default the following values are interpreted
        as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
        'n/a', 'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is True, and ``na_values`` are specified,
          ``na_values`` is appended to the default NaN values used for parsing.
        * If ``keep_default_na`` is True, and ``na_values`` are not specified, only
          the default NaN values are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are specified, only
          the NaN values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    parse_dates : bool, list-like, or dict, default False
        The behavior is as follows:

        * ``bool``. If True -> try parsing the index.
        * ``list`` of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * ``dict``, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index contains an unparsable date, the entire column or
        index will be returned unaltered as an object data type. If you don`t want to
        parse some cells as date just change their type in Excel to "Text".
        For non-standard datetime parsing, use ``pd.to_datetime`` after ``pd.read_excel``.

        Note: A fast-path exists for iso8601-formatted dates.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`to_datetime` as-needed.
    date_format : str or dict of column -> format, default ``None``
       If used in conjunction with ``parse_dates``, will parse dates according to this
       format. For anything more complex,
       please read in as ``object`` and then apply :func:`to_datetime` as-needed.

       .. versionadded:: 2.0.0
    thousands : str, default None
        Thousands separator for parsing string columns to numeric.  Note that
        this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.
    decimal : str, default '.'
        Character to recognize as decimal point for parsing string columns to numeric.
        Note that this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.(e.g. use ',' for European data).

        .. versionadded:: 1.4.0

    comment : str, default None
        Comments out remainder of line. Pass a character or characters to this
        argument to indicate comments in the input file. Any data between the
        comment string and the end of the current line is ignored.
    skipfooter : int, default 0
        Rows at the end to skip (0-indexed).
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). Behaviour is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
          (default).
        * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
          DataFrame.

        .. versionadded:: 2.0

    engine_kwargs : dict, optional
        Arbitrary keyword arguments passed to excel engine.

    Returns
    -------
    DataFrame or dict of DataFrames
        DataFrame from the passed in Excel file. See notes in sheet_name
        argument for more information on when a dict of DataFrames is returned.

    See Also
    --------
    DataFrame.to_excel : Write DataFrame to an Excel file.
    DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_fwf : Read a table of fixed-width formatted lines into DataFrame.

    Notes
    -----
    For specific information on the methods used for each Excel engine, refer to the pandas
    :ref:`user guide <io.excel_reader>`

    Examples
    --------
    The file can be read using the file name as string or an open file object:

    >>> pd.read_excel('tmp.xlsx', index_col=0)  # doctest: +SKIP
           Name  Value
    0   string1      1
    1   string2      2
    2  #Comment      3

    >>> pd.read_excel(open('tmp.xlsx', 'rb'),
    ...               sheet_name='Sheet3')  # doctest: +SKIP
       Unnamed: 0      Name  Value
    0           0   string1      1
    1           1   string2      2
    2           2  #Comment      3

    Index and header can be specified via the `index_col` and `header` arguments

    >>> pd.read_excel('tmp.xlsx', index_col=None, header=None)  # doctest: +SKIP
         0         1      2
    0  NaN      Name  Value
    1  0.0   string1      1
    2  1.0   string2      2
    3  2.0  #Comment      3

    Column types are inferred but can be explicitly specified

    >>> pd.read_excel('tmp.xlsx', index_col=0,
    ...               dtype={'Name': str, 'Value': float})  # doctest: +SKIP
           Name  Value
    0   string1    1.0
    1   string2    2.0
    2  #Comment    3.0

    True, False, and NA values, and thousands separators have defaults,
    but can be explicitly specified, too. Supply the values you would like
    as strings or lists of strings!

    >>> pd.read_excel('tmp.xlsx', index_col=0,
    ...               na_values=['string1', 'string2'])  # doctest: +SKIP
           Name  Value
    0       NaN      1
    1       NaN      2
    2  #Comment      3

    Comment lines in the excel input file can be skipped using the
    ``comment`` kwarg.

    >>> pd.read_excel('tmp.xlsx', index_col=0, comment='#')  # doctest: +SKIP
          Name  Value
    0  string1    1.0
    1  string2    2.0
    2     None    NaN

<br>

In [25]:
# converting data types with a dictionary
data_types = {"channel" : str,
              "store"   : str}


# instantiating the dataset as an object
diamonds = pd.read_excel(io         = file      ,
                         dtype      = data_types,   # applying new data types
                         usecols    = range(1, 8) ) # range object


# checking results
diamonds.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    409 non-null    float64
 1   color    409 non-null    int64
 2   clarity  409 non-null    int64
 3   cut      409 non-null    int64
 4   channel  409 non-null    object
 5   store    409 non-null    object
 6   price    409 non-null    int64
dtypes: float64(1), int64(4), object(2)
memory usage: 22.5+ KB

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
Notice that Python interpreted the string conversions as type <em>object</em>. This is normal, and stems from the fact that strings are the most fundamental of data types in Python. When Python is confused about a feature's data type, such as when a string conversion takes place, it defaults to type <em>object</em>. This is because strings can represent virtually anything.
<br>

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h2>Part III: Analyzing Anomalies with Descriptive Statistics</h2>

In general, our objectives with <strong>.describe(&nbsp;)</strong> are to address the following questions:

* Does the data align with its documentation?
* Are there any extreme values skewing the distribution of any features?

<br>
Additionally, we can seek to validate assumptions that were made in the <em>Finding the "Best" Diamond on a Budget</em> case study, such as:

* Is $5,795 a reasonable amount for a normal citizen of Chicago? In other words, is it close to the center of the distribution for price?
* Can a 5 on the color scale be perceived as normal? What about clarity? In other words, do these characteristics reflect what a normal diamond should look like?

<br>
<h3>Basic Use of .describe(&nbsp;)</h3>

As its name implies, the <strong>.describe(&nbsp;)</strong> method generates a set of descriptive statistics to help us better understand our data. In its most basic form, it will output statistics for all features that are of numeric types.

In [26]:
# crude example of .describe()
diamonds.describe()

            carat       color     clarity         cut         price
count  409.000000  409.000000  409.000000  409.000000    409.000000
mean     1.055968    4.227384    5.056235    0.376528   6488.229829
std      0.418013    1.810815    1.573141    0.485108   4414.425161
min      0.320000    1.000000    1.000000    0.000000    878.000000
25%      0.720000    3.000000    4.000000    0.000000   3490.000000
50%      1.020000    4.000000    5.000000    0.000000   5550.000000
75%      1.210000    6.000000    6.000000    1.000000   8089.000000
max      2.480000    9.000000    9.000000    1.000000  27575.000000

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
We're off to a good start, but it is highly recommended that we reduce the number of decimal places being outputted as <strong><font style="color:red">an unnecessary degree of precision is another form of data dumping.</font></strong> Note, however, that since the type conversions conducted earlier were successful, <em>channel</em>, and <em>store</em> have been omitted from this table, thus alleviating us from getting distracted with irrelevant information.
<br><br>
<h3>Properly Applying .describe(&nbsp;)</h3>

The <strong>.describe(&nbsp;)</strong> method can be broken down into two parts: 1) Descriptive statistics for numeric data, and 2) Summary information for non-numeric data.
<br>
<h4>a) Complete the code below to output descriptive statistics related to the numeric features of the diamonds dataset, rounded to two decimal places.</h4>

In [29]:
# descriptive statistics on numeric columns
diamonds.describe(include = 'number').round(decimals = 2)

        carat   color  clarity     cut     price
count  409.00  409.00   409.00  409.00    409.00
mean     1.06    4.23     5.06    0.38   6488.23
std      0.42    1.81     1.57    0.49   4414.43
min      0.32    1.00     1.00    0.00    878.00
25%      0.72    3.00     4.00    0.00   3490.00
50%      1.02    4.00     5.00    0.00   5550.00
75%      1.21    6.00     6.00    1.00   8089.00
max      2.48    9.00     9.00    1.00  27575.00

<br>
The output above is much cleaner, allowing us to analyze its information more efficiently. This table is also far more presentable, helping to show that we are organized and not cutting corners throughout our analysis. Now, let's run <strong>.describe(&nbsp;)</strong> on the non-numeric features of the dataset.
<br><br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h4>b) Complete the code below to output frequency information related to the non-numeric features of the diamonds dataset.</h4>
Note that you do not need to round the results.

In [30]:
# descriptive statistics on non-numeric columns
diamonds.describe(include = 'object')

       channel store
count      409   409
unique       3    11
top          2    10
freq       318   211

<br>

The output above does not provide a high degree of information related to the dataset's non-numeric features. For this reason, we generally also rely on the <em>pandas</em> Series method <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html">.value_counts(&nbsp;)</a>. This method works with both numeric and non-numeric data.


<div style = "width:image width px; font-size:80%; text-align:center;"><img src="https://github.com/chase-kusterer/BASD/blob/main/script_images/chapter-X3-object-describe-table.png?raw=1" width="400" height="400" style="padding-bottom:0.5em;"> <em>Figure 12.2: Explanation of .describe(&nbsp;) for non-numeric data.</em></div>

<br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h4>c) Apply .value_counts(&nbsp;) to channel.</h4>
Leave the optional arguments as they are when developing your code. Does it appear that each channel has equal representation in the dataset? What does this imply?

In [31]:
# applying value_counts to channel
diamonds['channel'].value_counts(normalize = False,
                    sort      = False,
                    ascending = False)

channel
0     43
1     48
2    318
Name: count, dtype: int64

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h4>d) Apply .value_counts(&nbsp;) to store.</h4>
Set the sort argument to True. Do any of the stores have less than 30 observations?

In [35]:
# applying value_counts to store
diamonds['store'].value_counts(normalize = False, # percentages
                sort      = True , # sort by frequencies
                ascending = False) # smallest value on top?

store
10    211
11    107
3      15
7      14
6      13
1      11
9       9
2       8
8       7
4       7
5       7
Name: count, dtype: int64

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h4>e) Apply .value_counts(&nbsp;) to color.</h4>
Set the normalize argument to True and round the results to three decimal places. Does it appear that this feature is (relatively) normally distributed?

In [36]:
# applying value_counts to color
diamonds['color'].value_counts(normalize = True ,
                sort      = False,
                ascending = False).round(decimals = 3)\
                                  .sort_index(axis = 0, # sorting index
                                              ascending = True)

color
1    0.073
2    0.142
3    0.142
4    0.176
5    0.176
6    0.193
7    0.083
8    0.012
9    0.002
Name: proportion, dtype: float64

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h4>f) Apply .value_counts(&nbsp;) to clarity.</h4>
Set the normalize argument to True and round the results to two decimal places. Does it appear that this feature is (relatively) normally distributed?

In [ ]:
# applying value_counts to clarity
____

~~~


          _____          
         /\    \         
        /::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/__\:::\    \    
   /::::\   \:::\    \   
  /::::::\   \:::\    \  
 /:::/\:::\   \:::\    \
/:::/  \:::\   \:::\____\
\::/    \:::\   \::/    /
 \/____/ \:::\   \/____/
          \:::\    \     
           \:::\____\    
            \::/    /    
             \/____/     
                         
                         
                         
                         
                         
          _____          
         /\    \         
        /::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/__\:::\    \    
   /::::\   \:::\    \   
  /::::::\   \:::\    \  
 /:::/\:::\   \:::\    \
/:::/  \:::\   \:::\____\
\::/    \:::\  /:::/    /
 \/____/ \:::\/:::/    /
          \::::::/    /  
           \::::/    /   
           /:::/    /    
          /:::/    /     
         /:::/    /      
        /:::/    /       
        \::/    /        
         \/____/         
                         
          _____          
         /\    \         
        /::\____\        
       /::::|   |        
      /:::::|   |        
     /::::::|   |        
    /:::/|::|   |        
   /:::/ |::|   |        
  /:::/  |::|   | _____  
 /:::/   |::|   |/\    \
/:: /    |::|   /::\____\
\::/    /|::|  /:::/    /
 \/____/ |::| /:::/    /
         |::|/:::/    /  
         |::::::/    /   
         |:::::/    /    
         |::::/    /     
         /:::/    /      
        /:::/    /       
        \::/    /        
         \/____/         
                         
      _____              
     /\    \             
    /::\    \            
    \:::\    \           
     \:::\    \          
      \:::\    \         
       \:::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/  \:::\____\    
   /:::/    \::/    /    
  /:::/    / \/____/     
 /:::/    /              
/:::/    /               
\::/    /                
 \/____/                 
                         
                         
                         
                         
                         
          _____          
         /\    \         
        /::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/__\:::\    \    
   /::::\   \:::\    \   
  /::::::\   \:::\    \  
 /:::/\:::\   \:::\    \
/:::/  \:::\   \:::\____\
\::/    \:::\  /:::/    /
 \/____/ \:::\/:::/    /
          \::::::/    /  
           \::::/    /   
           /:::/    /    
          /:::/    /     
         /:::/    /      
        /:::/    /       
        \::/    /        
         \/____/         
                         
          _____          
         /\    \         
        /::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/__\:::\    \    
    \:::\   \:::\    \   
  ___\:::\   \:::\    \  
 /\   \:::\   \:::\    \
/::\   \:::\   \:::\____\
\:::\   \:::\   \::/    /
 \:::\   \:::\   \/____/
  \:::\   \:::\    \     
   \:::\   \:::\____\    
    \:::\  /:::/    /    
     \:::\/:::/    /     
      \::::::/    /      
       \::::/    /       
        \::/    /        
         \/____/         
                         
      _____              
     /\    \             
    /::\    \            
    \:::\    \           
     \:::\    \          
      \:::\    \         
       \:::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/  \:::\____\    
   /:::/    \::/    /    
  /:::/    / \/____/     
 /:::/    /              
/:::/    /               
\::/    /                
 \/____/                 
                         
                         
                         
                         
                         
          _____          
         /\    \         
        /::\    \        
        \:::\    \       
         \:::\    \      
          \:::\    \     
           \:::\    \    
           /::::\    \   
  ____    /::::::\    \  
 /\   \  /:::/\:::\    \
/::\   \/:::/  \:::\____\
\:::\  /:::/    \::/    /
 \:::\/:::/    / \/____/
  \::::::/    /          
   \::::/____/           
    \:::\    \           
     \:::\    \          
      \:::\    \         
       \:::\____\        
        \::/    /        
         \/____/         
                         
          _____          
         /\    \         
        /::\    \        
       /::::\    \       
      /::::::\    \      
     /:::/\:::\    \     
    /:::/  \:::\    \    
   /:::/    \:::\    \   
  /:::/    / \:::\    \  
 /:::/    /   \:::\    \
/:::/____/     \:::\____\
\:::\    \      \::/    /
 \:::\    \      \/____/
  \:::\    \             
   \:::\    \            
    \:::\    \           
     \:::\    \          
      \:::\    \         
       \:::\____\        
        \::/    /        
         \/____/         
                         


~~~

<br>